apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configMap.yaml
  - mysql-deployment.yaml
  - mysql-auth-pv.yaml
  - mysql-auth-pvc.yaml
  - mysql-secret.yaml
  - mysql-svc.yaml