apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-{{.Values.name}}-deployment
  labels:
    app: mysql-{{.Values.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-{{.Values.name}} # fait réference au pod avec le label mysql-auth
  template:
    metadata:
      labels:
        app: mysql-{{.Values.name}} # label des pods créés, qui sera aussi utilisé par les services pour pouvoir les exposer
    spec:
      containers:
        - name: mysql-{{.Values.name}}-container
          image: mysql:8.0.0
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: mysql-{{.Values.name}}-cm
            - secretRef:
                name: mysql-{{.Values.name}}-secret

          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-{{.Values.name}}-data
      volumes:
        - name: mysql-{{.Values.name}}-data
          persistentVolumeClaim:
            claimName: mysql-{{.Values.name}}-pvc
