export enum Theme {
  CRYPTO='CRYPTO',
  STATISTIQUE = 'STATISTIQUE',
  DATA = 'DATA',
  MATHEMATIQUE = 'MATHEMATIQUE',
  PHYSIQUE = 'PHYSIQUE',
  PROGRAMMATION = 'PROGRAMMATION',
  CLOUD = 'CLOUD',
  COMPTABILITE = 'COMPTABILITE',
  GESTION = 'GESTION',
  BDD = 'BDD'
}
