apiVersion: v1
kind: Secret
metadata:
  name: smtp-secret
type: Opaque
stringData:
  SMTP_FROM_ADDRESS: "andjamihamid@gmail.com"
  SMTP_FROM_NAME: "EscaMiage"
  SMTP_USERNAME: "smtp-username"
  SMTP_PASSWORD: "smtp-password"