apiVersion: v1
kind: Service
metadata:
  name: {{.Values.discovery.name}}-svc
spec:
  ports:
    - name: amqp
      port: 8600
      targetPort: 8600
    - name: management
      port: 8500
      targetPort: 8500
  selector:
    app: {{.Values.discovery.name}}