version: '3.8'
services:
  bdd_jeu:
    image: mysql:latest
    container_name: bdd_jeu
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: escamiage
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: