name: actuality
replicas: 1
image:
  repository: service-actuality
  tag: "0.0.5"
  pullPolicy: ifNotPresent

customEnv:
  - name: SPRING_PROFILES_ACTIVE
    value: prod

database:
  enabled: true

containerPort: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

smtp:
  secret:
    exist: false
  config:
    exist: false

rabbitmq:
  enabled: true