name: auth
replicas: 1
image:
  repository: service-auth
  tag: "0.0.2"
  pullPolicy: ifNotPresent

mysql:
  password: auth-password
  rootPassword: auth-supers-secret
  user: auth-user

database:
  enabled: true

smtp:
  secret:
    exist: false
  config:
    exist: false

containerPort: 8080

customEnv:
  - name: SPRING_PROFILES_ACTIVE
    value: prod

rabbitmq:
  enabled: true


resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi