name: recompense
replicas: 1

image:
  repository: service-recompense
  tag: "0.0.2"
  pullPolicy: ifNotPresent

database:
  enabled: true

rabbitmq:
  enabled: true

smtp:
  secret:
    exist: false
  config:
    exist: false

containerPort: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi