apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-{{.Values.name}}-pv
spec:
  capacity:
    storage: {{.Values.volume.storage}}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{.Values.volume.hostPath}}