apiVersion: v1
kind: Secret
metadata:
  name: mysql-{{.Values.name}}-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "{{.Values.mysql.rootPassword}}"
  MYSQL_PASSWORD: "{{.Values.mysql.password}}"
